//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudades
    {
        public ciudades()
        {
            this.direcciones = new HashSet<direcciones>();
        }
    
        public int Id { get; set; }
        public string denominacion { get; set; }
    
        public virtual ICollection<direcciones> direcciones { get; set; }
    }
}
