//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int Id { get; set; }
        public string precio { get; set; }
        public string fecha { get; set; }
        public int medico_Id { get; set; }
        public int tipo_consulta_Id { get; set; }
        public int paciente_Id { get; set; }
    
        public virtual persona_medico persona_medico { get; set; }
        public virtual persona_paciente persona_paciente { get; set; }
        public virtual tipo_consulta tipo_consulta { get; set; }
    }
}
