//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_contacto
    {
        public int Id { get; set; }
        public string email_primario { get; set; }
        public string email_secundario { get; set; }
        public string tel_celular { get; set; }
        public string tel_fijo { get; set; }
        public int persona_Id { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
