//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public direcciones()
        {
            this.personas = new HashSet<personas>();
        }
    
        public int Id { get; set; }
        public string calle { get; set; }
        public Nullable<short> numero { get; set; }
        public string piso { get; set; }
        public Nullable<short> dpto { get; set; }
        public int ciudad_Id { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual ICollection<personas> personas { get; set; }
    }
}
