//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public direccion()
        {
            this.persona = new HashSet<persona>();
        }
    
        public int Id { get; set; }
        public string calle { get; set; }
        public Nullable<short> numero { get; set; }
        public string piso { get; set; }
        public Nullable<short> dpto { get; set; }
        public int ciudad_Id { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual ICollection<persona> persona { get; set; }
    }
}
