//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class consultoriosEntities : DbContext
    {
        public consultoriosEntities()
            : base("name=consultoriosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ciudades> ciudades { get; set; }
        public DbSet<consultas> consultas { get; set; }
        public DbSet<datos_contactos> datos_contactos { get; set; }
        public DbSet<direcciones> direcciones { get; set; }
        public DbSet<especialidades> especialidades { get; set; }
        public DbSet<obras_sociales> obras_sociales { get; set; }
        public DbSet<personas> personas { get; set; }
        public DbSet<personas_medico> personas_medico { get; set; }
        public DbSet<personas_paciente> personas_paciente { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipos_consultas> tipos_consultas { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
