//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class consultoriosEntities : DbContext
    {
        public consultoriosEntities()
            : base("name=consultoriosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ciudad> ciudad { get; set; }
        public DbSet<consulta> consulta { get; set; }
        public DbSet<datos_contacto> datos_contacto { get; set; }
        public DbSet<direccion> direccion { get; set; }
        public DbSet<especialidad> especialidad { get; set; }
        public DbSet<obra_social> obra_social { get; set; }
        public DbSet<persona> persona { get; set; }
        public DbSet<persona_medico> persona_medico { get; set; }
        public DbSet<persona_paciente> persona_paciente { get; set; }
        public DbSet<tipo_consulta> tipo_consulta { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
