//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra_social
    {
        public obra_social()
        {
            this.persona = new HashSet<persona>();
        }
    
        public int Id { get; set; }
        public string denominacion { get; set; }
        public string plus { get; set; }
    
        public virtual ICollection<persona> persona { get; set; }
    }
}
