//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class obras_sociales
    {
        public obras_sociales()
        {
            this.personas = new HashSet<personas>();
        }
    
        public int Id { get; set; }
        public string denominacion { get; set; }
        public string plus { get; set; }
    
        public virtual ICollection<personas> personas { get; set; }
    }
}
