//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.datos_contacto = new HashSet<datos_contacto>();
            this.obra_social = new HashSet<obra_social>();
        }
    
        public int Id { get; set; }
        public int dni { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> direccion_Id { get; set; }
    
        public virtual ICollection<datos_contacto> datos_contacto { get; set; }
        public virtual direccion direccion { get; set; }
        public virtual persona_medico persona_medico { get; set; }
        public virtual persona_paciente persona_paciente { get; set; }
        public virtual ICollection<obra_social> obra_social { get; set; }
    }
}
