//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_paciente
    {
        public persona_paciente()
        {
            this.consulta = new HashSet<consulta>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<consulta> consulta { get; set; }
        public virtual persona persona { get; set; }
    }
}
